[General]
# Nothing yet

[PluginExplorer]
Pause = false
Loop = true
Sound = true

[PluginExplorer.Key]
KeyboardToggle = 87 # F11

[PluginExplorer.Count]
Alchemy = 25
Ammo = 500
Armor = 5
Book = 5
Key = 1
Misc = 25
Note = 5
Weapon = 10

[MainMenu]
# Nothing yet

[MainMenu.UI]
Logo = false
Motd = false

[MainMenu.List]
CC = false
DLC = false
Mods = false
Credits = false
Help = false
