# You can override these settings either by editing this file or creating a QUI_Custom.toml file in the same location.
# References:
#     Key Codes: https://creationkit.com/index.php?title=Input_Script#DXScanCodes

[General]
# Nothing yet

[PluginExplorer]
Enable = true  # Enable PluginExplorer (default: true)
Pause = false  # Pause the game when the PluginExplorer interface is open (default: false)
Loop = true    # Reopens the PluginExplorer interface when the item container is closed (default: true)
Sound = true   # Unused (default: true)

[PluginExplorer.Key]
KeyboardToggle = 87 # F11

# Amount of items in the container per type
[PluginExplorer.Count]
Alchemy = 25
Ammo = 500
Armor = 1
Book = 1
Ingredient = 100
Key = 1
Misc = 25
Note = 5
Scroll = 1
Soul = 25
Spell = 1
Weapon = 1

[MainMenu]
Enable = true   # Enable MainMenu hooks and features (default: true)

[MainMenu.UI]
Logo = true     # Show the Bethesda logo (default: true)
Motd = true     # Show the Message of the Day (default: true)
Banner = true   # Show the Anniversary Edition banner (default: true)

[MainMenu.List]
CC = true       # Show the Creation Club entry (default: true)
DLC = false     # Show the DLC entry (default: false)
Mods = true     # Show the Mods entry (default: true)
Credits = true  # Show the Credits entry (default: true)
Help = true     # Show the Help entry (default: true)

[JournalMenu]
Enable = true   # Enable JournalMenu hooks and features (default: true)
DefaultPage = 2 # Sets the default page [0: QuestPage, 1: StatsPage, 2: SystemPage] (default: 2)
