[General]
# Nothing yet

[PluginExplorer]
Pause = false
Loop = true
Sound = true

[PluginExplorer.Key]
KeyboardToggle = 87 # F11 (https://creationkit.com/index.php?title=Input_Script#DXScanCodes)

[PluginExplorer.Count]
Alchemy = 25
Ammo = 500
Armor = 10
Book = 5
Ingredient = 100
Key = 1
Misc = 25
Note = 5
Spell = 1
Weapon = 10

[MainMenu]
# Nothing yet

[MainMenu.UI]
Logo = true
Motd = true

[MainMenu.List]
CC = true
DLC = false
Mods = true
Credits = true
Help = true
