# You can override these settings either by editing this file or creating a QUI_Custom.toml file in the same location.
# References:
#     Key Codes: https://creationkit.com/index.php?title=Input_Script#DXScanCodes

[General]
# Nothing yet

[PluginExplorer]
Pause = false  # Pause the game when the PluginExplorer interface is open (default: false)
Loop = true    # Reopens the PluginExplorer interface when the item container is closed (default: true)
Sound = true   # Unused (default: true)

[PluginExplorer.Key]
KeyboardToggle = 87 # F11

# Amount of items in the container per type
[PluginExplorer.Count]
Alchemy = 25
Ammo = 500
Armor = 1
Book = 1
Ingredient = 100
Key = 1
Misc = 25
Note = 5
Scroll = 1
Soul = 25
Spell = 1
Weapon = 1

[MainMenu]
# Nothing yet

[MainMenu.UI]
Logo = true    # Enable the Bethesda logo (default: true)
Motd = true    # Enable the Message of the Day (default: true)

[MainMenu.List]
CC = true      # Enable the Creation Club entry (default: true)
DLC = false    # Enable the DLC entry (default: false)
Mods = true    # Enable the Mods entry (default: true)
Credits = true # Enable the Credits entry (default: true)
Help = true    # Enable the Help entry (default: true)
