name: Main CI

on:
  push:
    branches: [ main, dev ]
    paths:
      - '.github/workflows/main_ci.yml'
      - 'res/**'
      - 'src/**'
      - 'xmake.lua'
      - 'xmake-requires.lock'
  pull_request:
    branches: [ main ]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: '>=2.7.1'

      - name: Build and Package
        run: |
          xmake package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ github.workspace }}/build/packages/**.zip
